language: java

git:
  quiet: false

before_install:
- brew install gradle
- gradle installWrapper

jobs:
  allow_failures:
  - os: osx
  include:
    - jdk: openjdk11
      os: linux
    - jdk: openjdk11
      os: osx

notifications:
  email:
    recipients: 
    - s4testei@uni-trier.de

script: ./gradlew buildCore
